BEGIN TRANSACTION;
CREATE TABLE 'wiki' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'name' TEXT, 'slug' TEXT, 'content' TEXT);
CREATE TABLE 'users' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'username' TEXT, 'password' TEXT, 'authlvl' INTEGER DEFAULT 0 );
COMMIT;
